#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '[Policy] Looking for lint errors'
npx lint-staged

if [ $? -ne 0 ]; then
    echo '[Policy ERROR] Found lint errors. Please fix before committing'
    exit 1
fi
